"""
PR Code Review Agent
Uses LangChain + Anthropic Claude to automatically review GitHub Pull Requests.
"""

import os
import sys
from pathlib import Path
from typing import Optional
from dotenv import load_dotenv
from langchain_anthropic import ChatAnthropic
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from github import Auth, Github, GithubException

load_dotenv()

# ── Configuration ──────────────────────────────────────────────────────────────
ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
MODEL_NAME = os.environ.get("MODEL_NAME", "claude-sonnet-4-6")
MAX_DIFF_CHARS = 12_000  # Truncate huge diffs to stay within context

# ── Prompt ─────────────────────────────────────────────────────────────────────
_PROMPT_FILE = Path(__file__).parent / "SYSTEM_PROMPT.md"
try:
    SYSTEM_PROMPT = _PROMPT_FILE.read_text(encoding="utf-8")
except FileNotFoundError:
    raise FileNotFoundError(f"System prompt file not found: {_PROMPT_FILE.resolve()}")

REVIEW_PROMPT = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            SYSTEM_PROMPT,
        ),
        (
            "human",
            """Please review this pull request.

**PR Title:** {title}
**PR Description:** {description}
**Repository:** {repo}
**Author:** {author}
**Files changed:** {files_changed}

**Diff:**
```diff
{diff}
```
""",
        ),
    ]
)


# ── LangChain chain ────────────────────────────────────────────────────────────
def build_review_chain():
    llm = ChatAnthropic(
        model=MODEL_NAME,
        anthropic_api_key=ANTHROPIC_API_KEY,
        max_tokens=2048,
    )
    return REVIEW_PROMPT | llm | StrOutputParser()


# ── Formatting helpers ────────────────────────────────────────────────────────
def format_review_header(pr_number: int, title: str) -> str:
    """Format a consistent header for the review output."""
    line = "═" * 70
    return f"{line}\n  PR #{pr_number}: {title}\n{line}"


# ── GitHub helpers ─────────────────────────────────────────────────────────────
def fetch_pr_data(repo_name: str, pr_number: int) -> dict:
    """Fetch PR metadata and diff from GitHub."""
    if GITHUB_TOKEN:
        g = Github(auth=Auth.Token(GITHUB_TOKEN))
    else:
        g = Github()
    try:
        repo = g.get_repo(repo_name)
        pr = repo.get_pull(pr_number)
    except GithubException as e:
        raise SystemExit(f"GitHub error: {e.data.get('message', e)}")

    # Collect diff from all changed files
    diff_parts = []
    files_changed = []
    for f in pr.get_files():
        files_changed.append(f.filename)
        if f.patch:
            diff_parts.append(f"--- {f.filename}\n{f.patch}")

    full_diff = "\n\n".join(diff_parts)
    if len(full_diff) > MAX_DIFF_CHARS:
        full_diff = full_diff[:MAX_DIFF_CHARS] + "\n\n[... diff truncated ...]"

    return {
        "title": pr.title,
        "description": pr.body or "(no description provided)",
        "repo": repo_name,
        "author": pr.user.login,
        "files_changed": ", ".join(files_changed) or "none",
        "diff": full_diff or "(no diff available)",
        "pr_object": pr,  # kept for posting comments
    }


def post_review_comment(pr, review_text: str, post_to_github: bool = False):
    """Optionally post the review back to the PR as a comment."""
    if not post_to_github:
        return
    pr.create_issue_comment(
        f"## 🤖 Automated Code Review\n\n{review_text}\n\n"
        "_Review generated by [pr-review-agent](https://github.com/SignaTrustDev/pr-review-agent)_"
    )
    print("✅  Review posted to GitHub PR.")


# ── Main entry point ───────────────────────────────────────────────────────────
def review_pr(
    repo_name: str,
    pr_number: int,
    post_comment: bool = False,
    output_file: Optional[str] = None,
):
    print(f"🔍  Fetching PR #{pr_number} from {repo_name} …")
    pr_data = fetch_pr_data(repo_name, pr_number)

    print(f"🤖  Running AI review with {MODEL_NAME} …")
    chain = build_review_chain()
    review = chain.invoke(
        {
            "title": pr_data["title"],
            "description": pr_data["description"],
            "repo": pr_data["repo"],
            "author": pr_data["author"],
            "files_changed": pr_data["files_changed"],
            "diff": pr_data["diff"],
        }
    )

    print("\n" + format_review_header(pr_number, pr_data['title']))
    print(review)
    print("═" * 70 + "\n")

    if output_file:
        with open(output_file, "w") as fh:
            fh.write(f"# Code Review – PR #{pr_number}\n\n{review}\n")
        print(f"📄  Review saved to {output_file}")

    post_review_comment(pr_data["pr_object"], review, post_to_github=post_comment)
    return review


# ── CLI ────────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="AI-powered GitHub PR reviewer")
    parser.add_argument("repo", help="owner/repo  e.g.  octocat/Hello-World")
    parser.add_argument("pr_number", type=int, help="Pull request number")
    parser.add_argument(
        "--post", action="store_true", help="Post review as a GitHub comment on the PR"
    )
    parser.add_argument(
        "--output", metavar="FILE", help="Save review to a markdown file"
    )
    args = parser.parse_args()

    if not ANTHROPIC_API_KEY:
        sys.exit("❌  Set ANTHROPIC_API_KEY environment variable.")

    review_pr(
        args.repo, args.pr_number, post_comment=args.post, output_file=args.output
    )